version: '3.8'

services:
  app:
    build: ./web
    volumes:
      - ./webapp:/usr/share/nginx/html
    ports:
      - 8080:80
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password

volumes:
  db-data:
    driver: local
